### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by jankapunkt** [Meteor-Community-Packages/mongo-collection-instances#37]
Before we start updating this package we should setup GitHub actions that run lint and tests

**Comment by dburles** [comment]
Minor gripe, if we adopt "standard" js style, can we leave semicolons in? I think it's a bit preposterous for a style standard to name itself "JavaScript Standard Style" and omit semicolons.

**Comment by jankapunkt** [comment]
Yes, standard is available with semicolons, named `semistandard` we could use that as well.
